"""edit tabel user

Revision ID: 4b2c6330a77c
Revises: 8208d5e9d80b
Create Date: 2024-01-22 15:34:31.517003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2c6330a77c'
down_revision = '8208d5e9d80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False), after='email')
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=False), after='phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
